apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-helm-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm
spec:
  project: default
  source:
    repoURL: https://github.com/Malek-Zaag/argocd-demo
    path: helm-webapp
    targetRevision: HEAD
    helm:
      releaseName: my-helm-app-release-name
      valueFiles:
      - values.yaml
      - values-dev.yaml
      - values-prod.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: helm-webapp-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true