apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-helm-app
  namespace: argocd
spec:
  project: default
  source:
    chart: 
    repoURL: https://github.com/Malek-Zaag/argocd-demo
    targetRevision: 0.1.0
    helm:
      releaseName: my-helm-app-release-name
  destination:
    server: "https://kubernetes.default.svc"
    namespace: helm-webapp-ns