apiVersion: v1
kind: Service
metadata:
  name: mywebapp
spec:
  ports:
  - port: 80
    protocol: TCP
    name: flask
    targetPort: 8080
  selector:
    app: myhelmapp
    tier: frontend
  type: NodePort